// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Room {
    "hostname": string;
    "addr": string;
    "port": number;
    "url": string;

    /** Creates a new Room instance. */
    constructor($$source: Partial<Room> = {}) {
        if (!("hostname" in $$source)) {
            this["hostname"] = "";
        }
        if (!("addr" in $$source)) {
            this["addr"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Room instance from a string or object.
     */
    static createFrom($$source: any = {}): Room {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Room($$parsedSource as Partial<Room>);
    }
}
