// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
  Create as $Create,
} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAvailableRooms(): $CancellablePromise<$models.Room[]> {
  return $Call.ByID(2675359888).then(($result: any) => {
    return $$createType1($result);
  });
}

export function MDNSLookup(): $CancellablePromise<void> {
  return $Call.ByID(2735963699);
}

export function String(): $CancellablePromise<string> {
  return $Call.ByID(1033622086);
}

// Private type creation functions
const $$createType0 = $models.Room.createFrom;
const $$createType1 = $Create.Array($$createType0);
